### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by marekm72**
s/singing/signing

### CODE REVIEW

**Comment by dd010101** [comment]
Perhaps I chosen wrong hobby.

**Comment by marekm72** [comment]
Not sure which is better/correct here - "chose" (past simple) or "have chosen" (present perfect)? :)

**Comment by dd010101** [comment]
Better?

BTW: the singing was there since the very beginning.... https://github.com/dd010101/vyos-jenkins/commit/3c9cf04104530c9c7b488230774f51139ae099d2#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R175 how did it survive that long I have no idea...

**Comment by marekm72** [comment]
No big deal, just something light for the weekend :)
There is one "singing key" in the vyos repo too - in infinitytier, inherited from zerotier.

**Comment by dd010101** [comment]
I just tried to search on github and found singing keyring, singing keys, singing password, shell scripts for singing, and also "singing up" page - whatever you can think of - it sings.

**Comment by marekm72** [comment]
Actually, there is also a term "singing key" - something about music and vocal range.  Some of these typos could be result of wrong auto-correct by some editors (if their "AI" was trained more on texts about music, not about cryptography).

**Pull request merged**
